welcome:
  message: Catalog Application running on Dev
spring:
  sql:
    init:
      mode: always
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/catalog
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  application:
    name: catalog
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8087


