welcome:
  message: Catalog Application running on Dev
spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
